version: '3.7'

services:
  # nginx - web server
  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    env_file: &env
      - ./app/.env
      - ./app/.env.local
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app:cached
  # php - personal home page
  php:
    build:
      context: .
      dockerfile: ./docker-config/alpine-php-dev-overlay/Dockerfile
    depends_on:
      - "db"
    env_file:
      *env
    expose:
      - "9000"
    links:
      - db
    volumes:
      - ./app:/var/www/app:consistent
  # postgre - database
  db:
    build:
      context: .
      dockerfile: ./docker-config/postgre/Dockerfile
    env_file:
      - ./env/.env-postgre
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
      - db-pgdata:/var/lib/postgresql/data

volumes:
  db-pgdata:
