<?php

namespace ContainerKrs297o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBusSearchProductService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Application\Product\Search\BusSearchProduct' shared autowired service.
     *
     * @return \App\Application\Product\Search\BusSearchProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Product/Search/BusSearchProduct.php';

        return $container->privates['App\\Application\\Product\\Search\\BusSearchProduct'] = new \App\Application\Product\Search\BusSearchProduct(($container->privates['App\\Infrastructure\\Adapter\\DBAL\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
