<?php

namespace ContainerKrs297o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDBALListProductCommandService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Application\Product\List\DBALListProductCommand' shared autowired service.
     *
     * @return \App\Application\Product\List\DBALListProductCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Product/List/DBALListProductCommand.php';

        $container->privates['App\\Application\\Product\\List\\DBALListProductCommand'] = $instance = new \App\Application\Product\List\DBALListProductCommand(($container->privates['App\\Infrastructure\\Adapter\\DBAL\\ProductRepository'] ?? $container->load('getProductRepositoryService')));

        $instance->setName('app:dbal-list-product');
        $instance->setDescription('Mock: list Product collection.');

        return $instance;
    }
}
