<?php

namespace ContainerKrs297o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetProductActionControllerService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\GetProductActionController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\GetProductActionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/GetProductActionController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/SearchProductResponder.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Bus/Query/QueryBus.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Bus/Query/InMemoryQueryBus.php';

        $container->services['App\\Infrastructure\\Http\\GetProductActionController'] = $instance = new \App\Infrastructure\Http\GetProductActionController(new \App\Infrastructure\Http\SearchProductResponder(), new \App\Infrastructure\Bus\Query\InMemoryQueryBus(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Application\\Product\\Search\\BusSearchProduct'] ?? $container->load('getBusSearchProductService'));
        }, 1)));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []))->withContext('App\\Infrastructure\\Http\\GetProductActionController', $container));

        return $instance;
    }
}
