<?php

namespace ContainerKrs297o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMockSearchProductCommandService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Application\Product\Search\MockSearchProductCommand' shared autowired service.
     *
     * @return \App\Application\Product\Search\MockSearchProductCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Product/Search/MockSearchProductCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/ProductInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Adapter/Mock/ProductRepository.php';

        $container->privates['App\\Application\\Product\\Search\\MockSearchProductCommand'] = $instance = new \App\Application\Product\Search\MockSearchProductCommand(($container->privates['App\\Infrastructure\\Adapter\\Mock\\ProductRepository'] ?? ($container->privates['App\\Infrastructure\\Adapter\\Mock\\ProductRepository'] = new \App\Infrastructure\Adapter\Mock\ProductRepository())));

        $instance->setName('app:mock-search-product');
        $instance->setDescription('Mock: search a Product.');

        return $instance;
    }
}
