<?php

namespace ContainerKrs297o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductPersisterService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Adapter\DBAL\ProductPersister' shared autowired service.
     *
     * @return \App\Infrastructure\Adapter\DBAL\ProductPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/symfony/var-exporter/LazyGhostTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Symfony/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Persister/ProductInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Adapter/DBAL/ProductPersister.php';

        return $container->privates['App\\Infrastructure\\Adapter\\DBAL\\ProductPersister'] = new \App\Infrastructure\Adapter\DBAL\ProductPersister(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
