<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPFRlx0z\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPFRlx0z/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerPFRlx0z.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerPFRlx0z\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerPFRlx0z\App_KernelLocalDebugContainer([
    'container.build_hash' => 'PFRlx0z',
    'container.build_id' => '40b3f6ef',
    'container.build_time' => 1677856739,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPFRlx0z');
