<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrs297o\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrs297o/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerKrs297o.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerKrs297o\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerKrs297o\App_KernelLocalDebugContainer([
    'container.build_hash' => 'Krs297o',
    'container.build_id' => 'ddb219d3',
    'container.build_time' => 1677847438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrs297o');
